#
#  ╔════════════════════════════════════════════════════════════════════════════════════════════════════════╗
#  ║ ██████╗░░█████╗░░█████╗░░██████╗████████╗███████╗░█████╗░░█████╗░███╗░░██╗░█████╗░███╗░░░███╗██╗░░░██╗ ║
#  ║ ██╔══██╗██╔══██╗██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗████╗░████║╚██╗░██╔╝ ║
#  ║ ██████╦╝██║░░██║██║░░██║╚█████╗░░░░██║░░░█████╗░░██║░░╚═╝██║░░██║██╔██╗██║██║░░██║██╔████╔██║░╚████╔╝░ ║
#  ║ ██╔══██╗██║░░██║██║░░██║░╚═══██╗░░░██║░░░██╔══╝░░██║░░██╗██║░░██║██║╚████║██║░░██║██║╚██╔╝██║░░╚██╔╝░░ ║
#  ║ ██████╦╝╚█████╔╝╚█████╔╝██████╔╝░░░██║░░░███████╗╚█████╔╝╚█████╔╝██║░╚███║╚█████╔╝██║░╚═╝░██║░░░██║░░░ ║
#  ║ ╚═════╝░░╚════╝░░╚════╝░╚═════╝░░░░╚═╝░░░╚══════╝░╚════╝░░╚════╝░╚═╝░░╚══╝░╚════╝░╚═╝░░░░░╚═╝░░░╚═╝░░░ ║
#  ╚════════════════════════════════════════════════════════════════════════════════════════════════════════╝
#
# Watch the full resource in GitHub
# https://github.com/ItsWagPvP/BoostEconomy.git
#
# Discord: https://discord.gg/x4mdfwWs8P
# www.boostdevteam.eu

# Do not change the version
Version: 1.3.4

# Fully customizable messages
Messages:
  General:
    NoPerms: "&b&lBoostEconomy &8» &cYou do not have enough permissions"
    NoConsole: "&b&lBoostEconomy &8» &cYou can't do this from console"
    NoPlayer: "&b&lBoostEconomy &8» &cYou can't do this from player!"
    Reload: "&b&lBoostEconomy &8» &aThe plugin has been reloaded with success! (%time%ms)"
    InvalidArgs: "&b&lBoostEconomy &8» &7Invalid args! /be <reload/help/checkforupdates/debug/discord>"
  Money:
    Chat: "&b&lMoney &8» &7You have &a%money%$"
    Done: "&b&lMoney &8» &aDone!"
    Refreshed: "&b&lMoney &8» &7Your money has been changed, now you have &a%money%$"
    Pay:
      Send: "&b&lMoney &8» &7You have sent &c%money%$ &7to &c%target%"
      Received: "&b&lMoney &8» &7You have received &c%money%$ &7from &c%player%"
    InvalidArgs:
      Pay: "&b&lMoney &8» &7Invalid args! /pay <player> <money>"
      Eco: "&b&lMoney &8» &7Invalid args! /eco <player> <set/take/give> <money>"
      Reset: "&b&lMoney &8» &7Invalid args! /ecoreset <player>"
    PlayerNotFound: "&b&lMoney &8» &cPlayer not found!"
    NoMoney: "&b&lMoney &8» &cYou do not have enough money!"
    Others: "&b&lMoney &8» &a%target% &7has &a%money%$"
    PayYourself: "&b&lMoney &8» &cYou can't pay yourself!"
    Resetted: "&b&lMoney &8» &7Your money has been restored to &c%money%$"
  BalTop:
    Header: "&c&lTop 10 balances"
    PlayerFormat: "&6%number%) &f&l%player%: &c%money%$"

# Settings
Config:

  # The format for the %boosteconomy_x_formatted%
  # 1000 = 1k
  # 100000000 = 1M
  # 100000000000 = 1B
  # 100000000000000000 = 1T
  # 100000000000000000000 = 1Q
  Format:
      k: "k"
      M: "M"
      B: "B"
      T: "T"
      Q: "Q"

  # Will write all the action of the plugin in the BoostEconomy/log.txt file
  Logs: true

  # Will hook with PlaceholderAPI and loads the placeholders
  Placeholders: true

  # Control if the plugin is outdated (Only works in 1.12+)
  CheckForUpdates:

    # The updater will send to the console if the plugin is outdated in the startup
    Console: true

    # The updater will send a message to the player that have the "boosteconomy.checkforupdates" permission
    Player: true

  # When a player join he will have this money by default
  StartMoney: 0.00

  # Send to the console the message of saving data
  ConsoleSaveMessage: true

  # Do you want to use sounds of success or error?
  UseSounds: true
  Sounds:

    # Played when a player do an action and it works fine
    Success: "ENTITY_PLAYER_LEVELUP"

    # Played when a player do an action and it don't works fine
    Error: "ENTITY_VILLAGER_NO"

GUI:

  # GUI Of /money
  Money:
    UseGUI: false
    Title: "&9&lMoney"

    # /money
    YourHead: "&cYou have %money%$"

    # /money <player>
    OthersHead: "&c%target% has %money%$"

  # GUI Of /baltop
  BalTop:
    UseGUI: false
    Title: "&9&lTop 10 balances"

    # The position in the baltop
    Number: "&b&l%number%°"

    # Description of the item
    Lore: "&f&l%player%: &c%money%"

# Banknotes system
Banknotes:

  # Enable banknotes?
  UseBanknotes: true

  # Which material do you want to use?
  Material: PAPER

  # If your server version is old and you have block ID it's like 100:10
  # The :10 is the data
  Data: 0

  # Name of the item
  Name: "&9Banknotes"

  # Do you want to use limits?
  Enable-Maximum: false
  Maximum-Withdraw-Amount: 100000000
  Enable-Minimum: false
  Minimun-Withdraw-Amount: 0

  # When console give with /banknotes give <name> <money>
  # The lore is "Withdrawn by Console"
  Console-Name: "Console"

  # Description of the item
  Lore:
    - "&7Value: &a%money%"
    - "&7Withdrawn by &a%player%"

  # Right-Click on air or to a block will deposit the banknote
  Allow-Right-Click-To-Deposit-Notes: true

  # Customizable messages
  Messages:
    Note-Redeemed: "&b&lBanknote &8» &7Banknote for &a%money%$ &7has been redeemed"
    Invalid-Number: "&b&lBanknote &8» &cThe number that you have inserted is invalid!"
    Less-Than-Minimum: "&b&lBanknote &8» &cThe number that you have inserted is lower than the minimum! (%min%)"
    More-than-Maximum: "&b&lBanknote &8» &cThe number that you have inserted is bigger than the maximum! (%max%)"
    Insufficient-Funds: "&b&lBanknote &8» &eYou don't have enough money!"
    Inventory-Full: "&b&lBanknote &8» &cYour inventory is full!"
    Note-Created: "&b&lBanknote &8» &7You have successfully created a banknotes of &a%money%$!"
    Player-Not-Found: "&b&lBanknote &8» &cPlayer not found!"
    Note-Received: "&b&lBanknote &8» &7You have received a banknote of &a%money%$&7 by &c%player%"
    Note-Given: "&b&lBanknote &8» &7You have given a banknotes of &c%money%$&7 to &a%player%"
    Invalid-Note: "&b&lBanknote &8» &cThe banknote is invalid"
    Nothing-In-Hand: "&b&lBanknote &8» &cYou don't have nothing in your hand!"

# For more options go in the mobs.yml file
Entity:

  # Do you want to use the MobReward function?
  Enable: true

  # Send message to the player when he kills an entity?
  SendMessage: true

  # KillMessage:
  KillMessage: "&b&lKill &8» &7You have killed &c%mob% &7and you have earned &a%money%$"
  
  # Enable ActionBar?
  ActionBar:

    # ActionBar message
    Message: "&fKilling &c%mob% &fyou've earned &e%money%€"
